---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: Trova informazioni sui problemi noti quando usi Trident con Docker. 
---
= Problemi noti e limitazioni
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trova informazioni sui problemi noti e sulle limitazioni quando si utilizza Trident con Docker.



== L'aggiornamento del plugin Trident Docker Volume alla versione 20.10 e successive da versioni precedenti provoca un errore di aggiornamento con l'errore "Nessun file o directory presente".

.Soluzione alternativa
. Disattivare il plugin.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. Rimuovere il plugin.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. Reinstallare il plugin fornendo l'extra `config` parametro.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




== I nomi dei volumi devono essere lunghi almeno 2 caratteri.


NOTE: Questa è una limitazione del client Docker.  Il client interpreterà il nome di un singolo carattere come un percorso Windows. https://github.com/moby/moby/issues/25773["Vedi bug 25773"^] .



== Docker Swarm presenta determinati comportamenti che impediscono a Trident di supportarlo con ogni combinazione di storage e driver.

* Attualmente Docker Swarm utilizza il nome del volume anziché l'ID del volume come identificatore univoco del volume.
* Le richieste di volume vengono inviate simultaneamente a ciascun nodo in un cluster Swarm.
* I plugin del volume (incluso Trident) devono essere eseguiti in modo indipendente su ciascun nodo in un cluster Swarm.  A causa del modo in cui funziona ONTAP e del modo in cui `ontap-nas` E `ontap-san` i driver funzionano, sono gli unici che riescono a operare entro questi limiti.


Gli altri driver sono soggetti a problemi come condizioni di gara che possono comportare la creazione di un gran numero di volumi per una singola richiesta senza un chiaro "vincitore"; ad esempio, Element ha una funzionalità che consente ai volumi di avere lo stesso nome ma ID diversi.

NetApp ha fornito feedback al team Docker, ma non ha alcuna indicazione di possibili ricorsi futuri.



== Se si sta predisponendo un FlexGroup , ONTAP non predispone un secondo FlexGroup se il secondo FlexGroup ha uno o più aggregati in comune con il FlexGroup in fase di provisioning.
