---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: 'Sono necessarie più istanze di Trident quando si desidera disporre contemporaneamente di più configurazioni di archiviazione.  La chiave per avere più istanze è assegnare loro nomi diversi utilizzando l"opzione --alias con il plugin containerizzato o l"opzione --volume-driver quando si crea un"istanza Trident sull"host.' 
---
= Gestisci più istanze Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono necessarie più istanze di Trident quando si desidera disporre contemporaneamente di più configurazioni di archiviazione.  La chiave per più istanze è dare loro nomi diversi usando il `--alias` opzione con il plugin containerizzato, oppure `--volume-driver` opzione durante l'istanziazione Trident sull'host.



== Passaggi per il plugin gestito da Docker (versione 1.13/17.03 o successiva)

. Avviare la prima istanza specificando un alias e un file di configurazione.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Avviare la seconda istanza, specificando un alias e un file di configurazione diversi.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Creare volumi specificando l'alias come nome del driver.
+
Ad esempio, per il volume dell'oro:

+
[source, console]
----
docker volume create -d gold --name ntapGold
----
+
Ad esempio, per il volume d'argento:

+
[source, console]
----
docker volume create -d silver --name ntapSilver
----




== Passaggi per la versione tradizionale (versione 1.12 o precedente)

. Avvia il plugin con una configurazione NFS utilizzando un ID driver personalizzato:
+
[source, console]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Avviare il plugin con una configurazione iSCSI utilizzando un ID driver personalizzato:
+
[source, console]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Fornire volumi Docker per ogni istanza del driver:
+
Ad esempio, per NFS:

+
[source, console]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Ad esempio, per iSCSI:

+
[source, console]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

