---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, nvme 
summary: Prima di poter distribuire Trident, è necessario installare e configurare i prerequisiti del protocollo necessari sul proprio host. 
---
= Prerequisiti per la distribuzione
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter distribuire Trident, è necessario installare e configurare i prerequisiti del protocollo necessari sul proprio host.



== Verificare i requisiti

* Verifica che la tua distribuzione soddisfi tutti i requisitilink:../trident-get-started/requirements.html["requisiti"] .
* Verifica di aver installato una versione supportata di Docker.  Se la tua versione di Docker non è aggiornata, https://docs.docker.com/engine/install/["installarlo o aggiornarlo"^] .
+
[source, console]
----
docker --version
----
* Verificare che i prerequisiti del protocollo siano installati e configurati sul proprio host.




=== Strumenti NFS

Installare gli strumenti NFS utilizzando i comandi per il sistema operativo in uso.

[role="tabbed-block"]
====
.RHEL 8+
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: Riavviare i nodi worker dopo aver installato gli strumenti NFS per evitare errori durante il collegamento dei volumi ai container.



=== strumenti iSCSI

Installare gli strumenti iSCSI utilizzando i comandi del sistema operativo in uso.

[role="tabbed-block"]
====
.RHEL 8+
--
. Installare i seguenti pacchetti di sistema:
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. Verificare che la versione di iscsi-initiator-utils sia 6.2.0.874-2.el7 o successiva:
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. Imposta la scansione su manuale:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Abilita multipathing:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Garantire `etc/multipath.conf` contiene `find_multipaths no` Sotto `defaults` .

. Assicurare che `iscsid` E `multipathd` stanno correndo:
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. Abilita e avvia `iscsi` :
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. Installare i seguenti pacchetti di sistema:
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. Verificare che la versione open-iscsi sia 2.0.874-5ubuntu2.10 o successiva (per bionic) o 2.0.874-7.1ubuntu6.1 o successiva (per focal):
+
[source, console]
----
dpkg -l open-iscsi
----
. Imposta la scansione su manuale:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Abilita multipathing:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Garantire `etc/multipath.conf` contiene `find_multipaths no` Sotto `defaults` .

. Assicurare che `open-iscsi` E `multipath-tools` sono abilitati e in esecuzione:
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== Strumenti NVMe

Installa gli strumenti NVMe utilizzando i comandi per il tuo sistema operativo.

[NOTE]
====
* NVMe richiede RHEL 9 o versione successiva.
* Se la versione del kernel del nodo Kubernetes è troppo vecchia o se il pacchetto NVMe non è disponibile per la versione del kernel, potrebbe essere necessario aggiornare la versione del kernel del nodo a una con il pacchetto NVMe.


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


== Strumenti FC

Installa gli strumenti FC utilizzando i comandi per il tuo sistema operativo.

* Quando si utilizzano nodi worker che eseguono RHEL/Red Hat Enterprise Linux CoreOS (RHCOS) con FC PV, specificare `discard` mountOption in StorageClass per eseguire il recupero dello spazio in linea. Fare riferimento a https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Documentazione Red Hat"^] .


[role="tabbed-block"]
====
.RHEL 8+
--
. Installare i seguenti pacchetti di sistema:
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. Abilita multipathing:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Garantire `etc/multipath.conf` contiene `find_multipaths no` Sotto `defaults` .

. Assicurare che `multipathd` è in esecuzione:
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. Installare i seguenti pacchetti di sistema:
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. Abilita multipathing:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Garantire `etc/multipath.conf` contiene `find_multipaths no` Sotto `defaults` .

. Assicurare che `multipath-tools` è abilitato e in esecuzione:
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====