---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Visualizza le opzioni di configurazione disponibili per le tue configurazioni Trident . 
---
= Opzioni di configurazione dell'archiviazione
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Visualizza le opzioni di configurazione disponibili per le tue configurazioni Trident .



== Opzioni di configurazione globali

Queste opzioni di configurazione si applicano a tutte le configurazioni Trident , indipendentemente dalla piattaforma di archiviazione utilizzata.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `version`  a| 
Numero di versione del file di configurazione
 a| 
`1`



| `storageDriverName`  a| 
Nome del driver di archiviazione
 a| 
`ontap-nas`, `ontap-san` , `ontap-nas-economy` ,
`ontap-nas-flexgroup` , `solidfire-san`



| `storagePrefix`  a| 
Prefisso facoltativo per i nomi dei volumi.  Predefinito: `netappdvp_` .
 a| 
`staging_`



| `limitVolumeSize`  a| 
Restrizione facoltativa sulle dimensioni del volume.  Predefinito: "" (non applicato)
 a| 
`10g`

|===

TIP: Non usare `storagePrefix` (incluso quello predefinito) per i backend Element.  Per impostazione predefinita, il `solidfire-san` il driver ignorerà questa impostazione e non utilizzerà un prefisso.  NetApp consiglia di utilizzare un tenantID specifico per la mappatura del volume Docker oppure di utilizzare i dati degli attributi popolati con la versione di Docker, le informazioni sul driver e il nome non elaborato di Docker nei casi in cui sia stato utilizzato un nome modificato.

Sono disponibili opzioni predefinite per evitare di doverle specificare su ogni volume creato.  IL `size` L'opzione è disponibile per tutti i tipi di controller.  Per un esempio su come impostare la dimensione predefinita del volume, vedere la sezione Configurazione ONTAP .

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `size`  a| 
Dimensione predefinita facoltativa per i nuovi volumi. Predefinito: `1G`
 a| 
`10G`

|===


== Configurazione ONTAP

Oltre ai valori di configurazione globali sopra indicati, quando si utilizza ONTAP, sono disponibili le seguenti opzioni di primo livello.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `managementLIF`  a| 
Indirizzo IP del LIF di gestione ONTAP .  È possibile specificare un nome di dominio completo (FQDN).
 a| 
`10.0.0.1`



| `dataLIF`  a| 
Indirizzo IP del protocollo LIF.

* Driver ONTAP NAS*: NetApp consiglia di specificare `dataLIF` .  Se non specificato, Trident recupera i dataLIF dall'SVM.  È possibile specificare un nome di dominio completo (FQDN) da utilizzare per le operazioni di montaggio NFS, consentendo di creare un DNS round-robin per bilanciare il carico su più dataLIF.

* Driver ONTAP SAN*: Non specificare per iSCSI o FC.  Usi Tridentlink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappa LUN selettiva ONTAP"^] per scoprire i LIF iSCSI o FC necessari per stabilire una sessione multi-percorso.  Viene generato un avviso se `dataLIF` è definito esplicitamente.
 a| 
`10.0.0.2`



| `svm`  a| 
Macchina virtuale di archiviazione da utilizzare (obbligatoria se il LIF di gestione è un LIF del cluster)
 a| 
`svm_nfs`



| `username`  a| 
Nome utente per connettersi al dispositivo di archiviazione
 a| 
`vsadmin`



| `password`  a| 
Password per connettersi al dispositivo di archiviazione
 a| 
`secret`



| `aggregate`  a| 
Aggregato per il provisioning (facoltativo; se impostato, deve essere assegnato all'SVM).  Per il `ontap-nas-flexgroup` driver, questa opzione viene ignorata.  Tutti gli aggregati assegnati all'SVM vengono utilizzati per effettuare il provisioning di un volume FlexGroup .
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Facoltativo, il provisioning fallisce se l'utilizzo è superiore a questa percentuale
 a| 
`75%`



| `nfsMountOptions`  a| 
Controllo dettagliato delle opzioni di montaggio NFS; il valore predefinito è "-o nfsvers=3".  *Disponibile solo per il `ontap-nas` E `ontap-nas-economy` autisti*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Vedi le informazioni sulla configurazione dell'host NFS qui"^] .
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident crea e gestisce per nodo `igroups` COME `netappdvp` .

Questo valore non può essere modificato o omesso.

*Disponibile solo per il `ontap-san` autista*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Dimensione massima del volume richiedibile.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Il numero massimo di qtree per FlexVol deve essere compreso nell'intervallo [50, 300], il valore predefinito è 200.

*Per il `ontap-nas-economy` driver, questa opzione consente di personalizzare il numero massimo di qtree per FlexVol*.
 a| 
`300`



 a| 
`sanType`
| *Supportato per `ontap-san` solo conducente.*  Utilizzare per selezionare `iscsi` per iSCSI, `nvme` per NVMe/TCP o `fcp` per SCSI su Fibre Channel (FC). | `iscsi`se vuoto 


| `limitVolumePoolSize` | *Supportato per `ontap-san-economy` E `ontap-san-economy` solo conducenti.*  Limita le dimensioni FlexVol nei driver ONTAP ontap-nas-economy e ontap-SAN-economy.  a| 
`300g`

|===
Sono disponibili opzioni predefinite per evitare di doverle specificare su ogni volume creato:

[cols="1,3,2"]
|===
| Opzione | Descrizione | Esempio 


| `spaceReserve`  a| 
Modalità di prenotazione dello spazio; `none` (sottile provisioning) o `volume` (spesso)
 a| 
`none`



| `snapshotPolicy`  a| 
Criterio di snapshot da utilizzare, l'impostazione predefinita è `none`
 a| 
`none`



| `snapshotReserve`  a| 
Percentuale di riserva snapshot, il valore predefinito è "" per accettare il valore predefinito ONTAP
 a| 
`10`



| `splitOnClone`  a| 
Dividere un clone dal suo genitore al momento della creazione, per impostazione predefinita `false`
 a| 
`false`



| `encryption`  a| 
Abilita NetApp Volume Encryption (NVE) sul nuovo volume; il valore predefinito è `false` .  Per utilizzare questa opzione, NVE deve essere concesso in licenza e abilitato sul cluster.

Se NAE è abilitato sul backend, qualsiasi volume fornito in Trident sarà abilitato per NAE.

Per maggiori informazioni, fare riferimento a:link:../trident-reco/security-reco.html["Come funziona Trident con NVE e NAE"] .
 a| 
VERO



| `unixPermissions`  a| 
Opzione NAS per volumi NFS forniti, impostazione predefinita `777`
 a| 
`777`



| `snapshotDir`  a| 
Opzione NAS per l'accesso al `.snapshot` elenco.
 a| 
"true" per NFSv4 "false" per NFSv3



| `exportPolicy`  a| 
Opzione NAS da utilizzare per la politica di esportazione NFS, predefinita `default`
 a| 
`default`



| `securityStyle`  a| 
Opzione NAS per l'accesso al volume NFS fornito.

Supporti NFS `mixed` E `unix` stili di sicurezza.  L'impostazione predefinita è `unix` .
 a| 
`unix`



| `fileSystemType`  a| 
Opzione SAN per selezionare il tipo di file system, il valore predefinito è `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Criterio di tiering da utilizzare, l'impostazione predefinita è `none` .
 a| 
`none`

|===


=== Opzioni di ridimensionamento

IL `ontap-nas` E `ontap-san` i driver creano un ONTAP FlexVol per ogni volume Docker.  ONTAP supporta fino a 1000 FlexVol per nodo del cluster con un massimo di 12.000 volumi FlexVol per cluster. Se i requisiti del volume Docker rientrano in tale limitazione, `ontap-nas` driver è la soluzione NAS preferita grazie alle funzionalità aggiuntive offerte da FlexVols, come gli snapshot Docker-volume-granular e la clonazione.

Se hai bisogno di più volumi Docker di quelli che possono essere gestiti dai limiti FlexVol , scegli `ontap-nas-economy` o il `ontap-san-economy` autista.

IL `ontap-nas-economy` il driver crea volumi Docker come Qtree ONTAP all'interno di un pool di volumi FlexVol gestiti automaticamente.  I Qtree offrono una scalabilità molto maggiore, fino a 100.000 per nodo del cluster e 2.400.000 per cluster, a scapito di alcune funzionalità.  IL `ontap-nas-economy` il driver non supporta snapshot Docker-volume-granular o clonazione.


NOTE: IL `ontap-nas-economy` Il driver non è attualmente supportato in Docker Swarm, perché Docker Swarm non orchestra la creazione di volumi su più nodi.

IL `ontap-san-economy` il driver crea volumi Docker come LUN ONTAP all'interno di un pool condiviso di volumi FlexVol gestiti automaticamente.  In questo modo, ogni FlexVol non è limitato a una sola LUN e offre una migliore scalabilità per i carichi di lavoro SAN.  A seconda dell'array di archiviazione, ONTAP supporta fino a 16384 LUN per cluster.  Poiché i volumi sono LUN sottostanti, questo driver supporta snapshot e clonazione Docker-volume-granular.

Scegli il `ontap-nas-flexgroup` driver per aumentare il parallelismo su un singolo volume che può crescere fino a raggiungere l'ordine dei petabyte con miliardi di file.  Alcuni casi d'uso ideali per FlexGroups includono AI/ML/DL, big data e analisi, build di software, streaming, repository di file e così via.  Trident utilizza tutti gli aggregati assegnati a una SVM durante il provisioning di un volume FlexGroup .  Il supporto FlexGroup in Trident deve tenere conto anche delle seguenti considerazioni:

* Richiede ONTAP versione 9.2 o successiva.
* Al momento in cui scriviamo, FlexGroups supporta solo NFS v3.
* Si consiglia di abilitare gli identificatori NFSv3 a 64 bit per SVM.
* La dimensione minima consigliata per il membro/volume FlexGroup è 100 GiB.
* La clonazione non è supportata per i volumi FlexGroup .


Per informazioni su FlexGroups e carichi di lavoro appropriati per FlexGroups, fare riferimento a https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Guida alle best practice e all'implementazione del volume NetApp FlexGroup"^] .

Per ottenere funzionalità avanzate e su larga scala nello stesso ambiente, è possibile eseguire più istanze del Docker Volume Plugin, una delle quali utilizzando `ontap-nas` e un altro usando `ontap-nas-economy` .



=== Ruolo ONTAP personalizzato per Trident

È possibile creare un ruolo cluster ONTAP con privilegi minimi in modo da non dover utilizzare il ruolo di amministratore ONTAP per eseguire operazioni in Trident.  Quando si include il nome utente in una configurazione backend Trident , Trident utilizza il ruolo del cluster ONTAP creato per eseguire le operazioni.

Fare riferimento alink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Generatore di ruoli personalizzati Trident"] per ulteriori informazioni sulla creazione di ruoli personalizzati Trident .

[role="tabbed-block"]
====
.Utilizzo di ONTAP CLI
--
. Crea un nuovo ruolo utilizzando il seguente comando:
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. Crea un nome utente per l'utente Trident :
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. Assegna il ruolo all'utente:
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Utilizzo di System Manager
--
Eseguire i seguenti passaggi in ONTAP System Manager:

. *Crea un ruolo personalizzato*:
+
.. Per creare un ruolo personalizzato a livello di cluster, selezionare *Cluster > Impostazioni*.
+
(Oppure) Per creare un ruolo personalizzato a livello SVM, selezionare *Archiviazione > VM di archiviazione > `required SVM` > Impostazioni > Utenti e ruoli*.

.. Selezionare l'icona della freccia (*->*) accanto a *Utenti e ruoli*.
.. Selezionare *+Aggiungi* in *Ruoli*.
.. Definisci le regole per il ruolo e clicca su *Salva*.


. *Assegnare il ruolo all'utente Trident *: + Eseguire i seguenti passaggi nella pagina *Utenti e ruoli*:
+
.. Selezionare Aggiungi icona *+* in *Utenti*.
.. Selezionare il nome utente richiesto e selezionare un ruolo nel menu a discesa per *Ruolo*.
.. Fare clic su *Salva*.




--
====
Per maggiori informazioni consultare le seguenti pagine:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Ruoli personalizzati per l'amministrazione di ONTAP"^]Olink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Definisci ruoli personalizzati"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Lavorare con ruoli e utenti"^]




=== Esempio di file di configurazione ONTAP

.Esempio NFS per il driver <code>ontap-nas</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.Esempio NFS per il driver <code>ontap-nas-flexgroup</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.Esempio NFS per il driver <code>ontap-nas-economy</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.Esempio iSCSI per il driver <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.Esempio NFS per il driver <code>ontap-san-economy</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.Esempio NVMe/TCP per il driver <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.Esempio SCSI su FC per il driver <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Configurazione del software Element

Oltre ai valori di configurazione globali, quando si utilizza il software Element (NetApp HCI/ SolidFire), sono disponibili queste opzioni.

[cols="3*"]
|===
| Opzione | Descrizione | Esempio 


| `Endpoint`  a| 
\https://<login>:<password>@<mvip>/json-rpc/<versione-elemento>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Indirizzo IP e porta iSCSI
 a| 
10.0.0.7:3260



| `TenantName`  a| 
Tenant SolidFireF da utilizzare (creato se non trovato)
 a| 
`docker`



| `InitiatorIFace`  a| 
Specificare l'interfaccia quando si limita il traffico iSCSI all'interfaccia non predefinita
 a| 
`default`



| `Types`  a| 
Specifiche QoS
 a| 
Vedi esempio qui sotto



| `LegacyNamePrefix`  a| 
Prefisso per le installazioni Trident aggiornate.  Se hai utilizzato una versione di Trident precedente alla 1.3.2 e esegui un aggiornamento con volumi esistenti, dovrai impostare questo valore per accedere ai vecchi volumi mappati tramite il metodo volume-name.
 a| 
`netappdvp-`

|===
IL `solidfire-san` il driver non supporta Docker Swarm.



=== File di configurazione del software Element di esempio

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----