---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: 'Per creare volumi, utilizzare lo standard `docker volume` comandi con il nome del driver Trident specificato quando necessario.' 
---
= Lavorare con i volumi
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare, clonare e rimuovere facilmente volumi utilizzando lo standard `docker volume` comandi con il nome del driver Trident specificato quando necessario.



== Crea un volume

* Creare un volume con un driver utilizzando il nome predefinito:
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* Crea un volume con un'istanza Trident specifica:
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: Se non specifichi alcunlink:volume-driver-options.html["opzioni"^] , vengono utilizzati i valori predefiniti per il driver.

* Sostituisci la dimensione predefinita del volume. Per creare un volume da 20 GiB con un driver, vedi l'esempio seguente:
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: Le dimensioni del volume sono espresse come stringhe contenenti un valore intero con unità facoltative (esempio: 10 G, 20 GB, 3 TiB).  Se non viene specificata alcuna unità, l'impostazione predefinita è G. Le unità di misura possono essere espresse come potenze di 2 (B, KiB, MiB, GiB, TiB) o come potenze di 10 (B, KB, MB, GB, TB).  Le unità abbreviate utilizzano potenze di 2 (G = GiB, T = TiB, …).





== Rimuovere un volume

* Rimuovi il volume come qualsiasi altro volume Docker:
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: Quando si utilizza il `solidfire-san` driver, l'esempio precedente elimina e ripulisce il volume.



Per aggiornare Trident per Docker, procedere come segue.



== Clonare un volume

Quando si utilizza il `ontap-nas` , `ontap-san` , `solidfire-san` , E `gcp-cvs storage drivers` , Trident può clonare i volumi.  Quando si utilizza il `ontap-nas-flexgroup` O `ontap-nas-economy` driver, la clonazione non è supportata.  La creazione di un nuovo volume da un volume esistente comporterà la creazione di un nuovo snapshot.

* Ispezionare il volume per enumerare gli snapshot:
+
[source, console]
----
docker volume inspect <volume_name>
----
* Crea un nuovo volume da un volume esistente.  Verrà creato un nuovo snapshot:
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* Crea un nuovo volume da uno snapshot esistente su un volume.  Questo non creerà un nuovo snapshot:
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== Esempio

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== Accedi ai volumi creati esternamente

È possibile accedere ai dispositivi a blocchi creati esternamente (o ai loro cloni) tramite contenitori che utilizzano Trident *solo* se non hanno partizioni e se il loro file system è supportato da Trident (ad esempio: un `ext4` -formattato `/dev/sdc1` non sarà accessibile tramite Trident).
