---
sidebar: sidebar 
permalink: get-help.html 
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket 
summary: NetApp fornisce supporto per Trident in vari modi.  Sono disponibili ampie opzioni di auto-assistenza gratuite 24 ore su 24, 7 giorni su 7, come un canale Discord. 
---
= Supporto
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp fornisce supporto per Trident in vari modi.  Sono disponibili ampie opzioni di auto-assistenza gratuite 24 ore su 24, 7 giorni su 7, come articoli della knowledge base (KB) e un canale Discord.



== Supporto Trident

Trident offre tre livelli di supporto in base alla versione. Fare riferimento alink:https://mysupport.netapp.com/site/info/version-support["Supporto della versione software NetApp per le definizioni"^] .

Supporto completo:: Trident fornisce supporto completo per dodici mesi dalla data di rilascio.
Supporto limitato:: Trident fornisce supporto limitato per i mesi dal 13° al 24° dalla data di rilascio.
Autosufficienza:: La documentazione Trident sarà disponibile per i mesi dal 25° al 36° dalla data di uscita.


[cols="1, 1, 1, 1"]
|===


| Versione | Supporto completo | Supporto limitato | Autosufficienza 


 a| 
link:https://docs.netapp.com/us-en/trident/index.html["25,06"^]
| Giugno 2026 | Giugno 2027 | Giugno 2028 


 a| 
link:https://docs.netapp.com/us-en/trident-2502/index.html["25,02"^]
| Febbraio 2026 | Febbraio 2027 | Febbraio 2028 


 a| 
link:https://docs.netapp.com/us-en/trident-2410/index.html["24,10"^]
| Ottobre 2025 | Ottobre 2026 | Ottobre 2027 


 a| 
link:https://docs.netapp.com/us-en/trident-2406/index.html["24,06"^]
| Giugno 2025 | Giugno 2026 | Giugno 2027 


 a| 
link:https://docs.netapp.com/us-en/trident-2402/index.html["24,02"^]
| Febbraio 2025 | Febbraio 2026 | Febbraio 2027 


 a| 
link:https://docs.netapp.com/us-en/trident-2310/index.html["23,10"^]
| -- | Ottobre 2025 | Ottobre 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2307/index.html["23,07"^]
| -- | Luglio 2025 | Luglio 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2304/index.html["23,04"^]
| -- | Aprile 2025 | Aprile 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2301/index.html["23,01"^]
| -- | -- | Gennaio 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2210/index.html["22,10"^]
| -- | -- | Ottobre 2025 
|===


== Autosufficienza

Per un elenco completo degli articoli sulla risoluzione dei problemi, fare riferimento a https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes["Knowledgebase NetApp (richiesto accesso)"^] .



== Supporto della comunità

Esiste una vivace comunità pubblica di utenti di container (inclusi gli sviluppatori Trident ) sul nostrolink:https://discord.gg/NetApp["Canale Discord"^] .  Questo è il posto ideale per porre domande generali sul progetto e discutere di argomenti correlati con colleghi che la pensano come te.



== Supporto tecnico NetApp

Per assistenza con Trident, crea un pacchetto di supporto utilizzando `tridentctl logs -a -n trident` e inviarlo a `NetApp Support <Getting Help>` .



== Per maggiori informazioni

* link:https://github.com/NetApp/trident["Risorse Trident"^]
* link:https://cloud.netapp.com/kubernetes-hub["Hub Kubernetes"^]

