---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, Trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: Per disinstallare Trident dovresti usare lo stesso metodo che hai usato per installare Trident.  Se hai bisogno di correggere bug riscontrati dopo un aggiornamento, problemi di dipendenza o un aggiornamento non riuscito o incompleto, dovresti disinstallare Trident e reinstallare la versione precedente seguendo le istruzioni specifiche per quella versione. 
---
= Disinstallare Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per disinstallare Trident dovresti usare lo stesso metodo che hai usato per installare Trident.

.Informazioni su questo compito
* Se hai bisogno di una correzione per i bug osservati dopo un aggiornamento, problemi di dipendenza o un aggiornamento non riuscito o incompleto, dovresti disinstallare Trident e reinstallare la versione precedente utilizzando le istruzioni specifiche per quellalink:../earlier-versions.html["versione"] .  Questo è l'unico metodo consigliato per effettuare il _downgrade_ a una versione precedente.
* Per facilitare l'aggiornamento e la reinstallazione, la disinstallazione Trident non rimuove i CRD o gli oggetti correlati creati da Trident.  Se è necessario rimuovere completamente Trident e tutti i suoi dati, fare riferimento alink:../troubleshooting.html#completely-remove-trident-and-crds["Rimuovere completamente Trident e CRD"] .


.Prima di iniziare
Se si desidera dismettere i cluster Kubernetes, è necessario eliminare tutte le applicazioni che utilizzano volumi creati da Trident prima della disinstallazione.  Ciò garantisce che i PVC non vengano pubblicati sui nodi Kubernetes prima di essere eliminati.



== Determinare il metodo di installazione originale

Per disinstallare Trident dovresti usare lo stesso metodo che hai usato per installarlo.  Prima di disinstallare, verifica quale versione hai utilizzato per installare originariamente Trident.

. Utilizzo `kubectl get pods -n trident` per esaminare i baccelli.
+
** Se non è presente alcun pod operatore, Trident è stato installato utilizzando `tridentctl` .
** Se è presente un pod operatore, Trident è stato installato utilizzando l'operatore Trident manualmente o tramite Helm.


. Se è presente un pod operatore, utilizzare `kubectl describe tproc trident` per determinare se Trident è stato installato tramite Helm.
+
** Se è presente un'etichetta Helm, Trident è stato installato tramite Helm.
** Se non è presente alcuna etichetta Helm, Trident è stato installato manualmente utilizzando l'operatore Trident .






== Disinstallare un'installazione dell'operatore Trident

È possibile disinstallare manualmente un'installazione dell'operatore Trident oppure tramite Helm.



=== Disinstallare l'installazione manuale

Se hai installato Trident tramite l'operatore, puoi disinstallarlo eseguendo una delle seguenti operazioni:

. **Modificare `TridentOrchestrator` CR e imposta il flag di disinstallazione**:
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
Quando il `uninstall` la bandiera è impostata su `true` , l'operatore Trident disinstalla Trident, ma non rimuove TridentOrchestrator stesso.  Se vuoi installare nuovamente Trident, dovresti pulire TridentOrchestrator e crearne uno nuovo.

. **Eliminare `TridentOrchestrator` **: Rimuovendo il `TridentOrchestrator` CR utilizzato per distribuire Trident, si chiede all'operatore di disinstallare Trident.  L'operatore elabora la rimozione di `TridentOrchestrator` e procede alla rimozione della distribuzione e del daemonset Trident , eliminando i pod Trident creati come parte dell'installazione.
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== Disinstallare l'installazione di Helm

Se hai installato Trident tramite Helm, puoi disinstallarlo tramite `helm uninstall` .

[listing]
----
#List the Helm release corresponding to the Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== Disinstallare un `tridentctl` installazione

Utilizzare il `uninstall` comando in `tridentctl` per rimuovere tutte le risorse associate a Trident, ad eccezione dei CRD e degli oggetti correlati:

[listing]
----
./tridentctl uninstall -n <namespace>
----