---
sidebar: sidebar 
permalink: trident-use/anf-prep.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, active directory, csi proxy, aks, managed identities 
summary: Prima di poter configurare il backend di Azure NetApp Files , è necessario assicurarsi che siano soddisfatti i seguenti requisiti. 
---
= Prepararsi a configurare un backend di Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter configurare il backend di Azure NetApp Files , è necessario assicurarsi che siano soddisfatti i seguenti requisiti.



== Prerequisiti per i volumi NFS e SMB

Se si utilizza Azure NetApp Files per la prima volta o in una nuova posizione, è necessaria una configurazione iniziale per impostare Azure NetApp Files e creare un volume NFS. Fare riferimento a https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes["Azure: configura Azure NetApp Files e crea un volume NFS"^] .

Per configurare e utilizzare un https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^] backend, hai bisogno di quanto segue:

[NOTE]
====
* `subscriptionID`, `tenantID` , `clientID` , `location` , E `clientSecret` sono facoltativi quando si utilizzano identità gestite su un cluster AKS.
* `tenantID`, `clientID` , E `clientSecret` sono facoltativi quando si utilizza un'identità cloud su un cluster AKS.


====
* Un bacino di capacità. Fare riferimento alink:https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-set-up-capacity-pool["Microsoft: creare un pool di capacità per Azure NetApp Files"^] .
* Una subnet delegata ad Azure NetApp Files. Fare riferimento alink:https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["Microsoft: delegare una subnet ad Azure NetApp Files"^] .
* `subscriptionID`da una sottoscrizione Azure con Azure NetApp Files abilitato.
* `tenantID`, `clientID` , E `clientSecret` da unlink:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal["Registrazione dell'app"^] in Azure Active Directory con autorizzazioni sufficienti per il servizio Azure NetApp Files .  La registrazione dell'app deve utilizzare:
+
** Il ruolo di Proprietario o Collaboratorelink:https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["predefinito da Azure"^] .
** UNlink:https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-portal["ruolo di collaboratore personalizzato"] a livello di abbonamento(`assignableScopes` ) con le seguenti autorizzazioni limitate solo a quanto richiesto Trident .  Dopo aver creato il ruolo personalizzato,link:https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal["assegnare il ruolo utilizzando il portale di Azure"^] .
+
.Ruolo di collaboratore personalizzato
[%collapsible]
====
[source, JSON]
----
{
  "id": "/subscriptions/<subscription-id>/providers/Microsoft.Authorization/roleDefinitions/<role-definition-id>",
  "properties": {
    "roleName": "custom-role-with-limited-perms",
    "description": "custom role providing limited permissions",
    "assignableScopes": [
      "/subscriptions/<subscription-id>"
    ],
    "permissions": [
      {
        "actions": [
          "Microsoft.NetApp/netAppAccounts/capacityPools/read",
          "Microsoft.NetApp/netAppAccounts/capacityPools/write",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/read",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/write",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/delete",
          "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/MountTargets/read",
          "Microsoft.Network/virtualNetworks/read",
          "Microsoft.Network/virtualNetworks/subnets/read",
          "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/read",
          "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/write",
          "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/delete",
          "Microsoft.Features/features/read",
          "Microsoft.Features/operations/read",
          "Microsoft.Features/providers/features/read",
          "Microsoft.Features/providers/features/register/action",
          "Microsoft.Features/providers/features/unregister/action",
          "Microsoft.Features/subscriptionFeatureRegistrations/read"
        ],
        "notActions": [],
        "dataActions": [],
        "notDataActions": []
      }
    ]
  }
}
----
====


* L'azzurro `location` che contiene almeno uno https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["sottorete delegata"^] .  A partire dal Trident 22.01, il `location` Il parametro è un campo obbligatorio al livello superiore del file di configurazione del backend.  I valori di posizione specificati nei pool virtuali vengono ignorati.
* Per usare `Cloud Identity` , ottenere il `client ID` da un https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities["identità gestita assegnata dall'utente"^] e specificare quell'ID in `azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx` .




== Requisiti aggiuntivi per i volumi SMB

Per creare un volume SMB, è necessario disporre di:

* Active Directory configurato e connesso ad Azure NetApp Files. Fare riferimento alink:https://learn.microsoft.com/en-us/azure/azure-netapp-files/create-active-directory-connections["Microsoft: creare e gestire connessioni Active Directory per Azure NetApp Files"^] .
* Un cluster Kubernetes con un nodo controller Linux e almeno un nodo worker Windows che esegue Windows Server 2022.  Trident supporta volumi SMB montati su pod in esecuzione solo su nodi Windows.
* Almeno un segreto Trident contenente le credenziali di Active Directory, in modo che Azure NetApp Files possa autenticarsi in Active Directory.  Per generare segreto `smbcreds` :
+
[listing]
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='password'
----
* Un proxy CSI configurato come servizio Windows.  Per configurare un `csi-proxy` , fare riferimento alink:https://github.com/kubernetes-csi/csi-proxy["GitHub: Proxy CSI"^] Olink:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md["GitHub: Proxy CSI per Windows"^] per i nodi Kubernetes in esecuzione su Windows.

