---
sidebar: sidebar 
permalink: trident-use/create-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: È possibile progettare un file StorageClass di Kubernetes e creare StorageClass per indicare a Trident come effettuare il provisioning dei volumi. 
---
= Creare una classe di archiviazione
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configurare un oggetto StorageClass di Kubernetes e creare la classe di archiviazione per indicare a Trident come effettuare il provisioning dei volumi.



== Configurare un oggetto StorageClass di Kubernetes

IL https://kubernetes.io/docs/concepts/storage/storage-classes/["Oggetto StorageClass di Kubernetes"^] identifica Trident come il provisioner utilizzato per quella classe e indica a Trident come effettuare il provisioning di un volume. Per esempio:

[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
mountOptions:
  - nfsvers=3
  - nolock
parameters:
  backendType: "ontap-nas"
  media: "ssd"
allowVolumeExpansion: true
volumeBindingMode: Immediate
----
Fare riferimento alink:../trident-reference/objects.html["Oggetti Kubernetes e Trident"] per i dettagli su come le classi di archiviazione interagiscono con `PersistentVolumeClaim` e parametri per controllare il modo in cui Trident approvvigiona i volumi.



== Creare una classe di archiviazione

Dopo aver creato l'oggetto StorageClass, è possibile creare la classe di archiviazione. <<Campioni di classe di archiviazione>> fornisce alcuni esempi di base che puoi utilizzare o modificare.

.Passi
. Questo è un oggetto Kubernetes, quindi usa `kubectl` per crearlo in Kubernetes.
+
[listing]
----
kubectl create -f sample-input/storage-class-basic-csi.yaml
----
. Ora dovresti vedere una classe di archiviazione *basic-csi* sia in Kubernetes che in Trident e Trident dovrebbe aver rilevato i pool sul backend.
+
[source, console]
----
kubectl get sc basic-csi
----


[listing]
----
NAME         PROVISIONER             AGE
basic-csi    csi.trident.netapp.io   15h
----
[source, console]
----
./tridentctl -n trident get storageclass basic-csi -o json
----
[source, json]
----
{
  "items": [
    {
      "Config": {
        "version": "1",
        "name": "basic-csi",
        "attributes": {
          "backendType": "ontap-nas"
        },
        "storagePools": null,
        "additionalStoragePools": null
      },
      "storage": {
        "ontapnas_10.0.0.1": [
          "aggr1",
          "aggr2",
          "aggr3",
          "aggr4"
        ]
      }
    }
  ]
}
----


=== Campioni di classe di archiviazione

Trident fornisce https://github.com/NetApp/trident/tree/master/trident-installer/sample-input/storage-class-samples["definizioni di classi di archiviazione semplici per backend specifici"^] .

In alternativa, puoi modificare `sample-input/storage-class-csi.yaml.templ` file fornito con il programma di installazione e sostituisci `__BACKEND_TYPE__` con il nome del driver di archiviazione.

[listing]
----
./tridentctl -n trident get backend
+-------------+----------------+--------------------------------------+--------+---------+
|    NAME     | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------+----------------+--------------------------------------+--------+---------+
| nas-backend | ontap-nas      | 98e19b74-aec7-4a3d-8dcf-128e5033b214 | online |       0 |
+-------------+----------------+--------------------------------------+--------+---------+

cp sample-input/storage-class-csi.yaml.templ sample-input/storage-class-basic-csi.yaml

# Modify __BACKEND_TYPE__ with the storage driver field above (e.g., ontap-nas)
vi sample-input/storage-class-basic-csi.yaml
----