---
sidebar: sidebar 
permalink: trident-use/gcnv-prep.html 
keywords: trident backend, google cloud netapp volumes, smb volumes, active directory, csi proxy, aks, cloud identity 
summary: Prima di poter configurare il backend di Google Cloud NetApp Volumes , è necessario assicurarsi che siano soddisfatti i seguenti requisiti. 
---
= Preparati a configurare un backend Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di poter configurare il backend di Google Cloud NetApp Volumes , è necessario assicurarsi che siano soddisfatti i seguenti requisiti.



== Prerequisiti per i volumi NFS

Se si utilizza Google Cloud NetApp Volumes per la prima volta o in una nuova posizione, è necessaria una configurazione iniziale per impostare Google Cloud NetApp Volumes e creare un volume NFS. Fare riferimento alink:https://cloud.google.com/netapp/volumes/docs/before-you-begin/application-resilience["Prima di iniziare"^] .

Prima di configurare il backend di Google Cloud NetApp Volumes, assicurati di disporre di quanto segue:

* Un account Google Cloud configurato con il servizio Google Cloud NetApp Volumes . Fare riferimento alink:https://cloud.google.com/netapp-volumes["Google Cloud NetApp Volumes"^] .
* Numero di progetto del tuo account Google Cloud. Fare riferimento alink:https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects["Identificazione dei progetti"^] .
* Un account di servizio Google Cloud con NetApp Volumes Admin(`roles/netapp.admin` ) ruolo. Fare riferimento alink:https://cloud.google.com/netapp/volumes/docs/get-started/configure-access/iam#roles_and_permissions["Ruoli e autorizzazioni di gestione dell'identità e dell'accesso"^] .
* File chiave API per il tuo account GCNV.  Fare riferimento alink:https://cloud.google.com/iam/docs/keys-create-delete#creating["Crea una chiave dell'account di servizio"^]
* Un pool di stoccaggio. Fare riferimento alink:https://cloud.google.com/netapp/volumes/docs/configure-and-use/storage-pools/overview["Panoramica dei pool di archiviazione"^] .


Per ulteriori informazioni su come configurare l'accesso a Google Cloud NetApp Volumes, fare riferimento alink:https://cloud.google.com/netapp/volumes/docs/get-started/configure-access/workflow#before_you_begin["Configurare l'accesso a Google Cloud NetApp Volumes"^] .
