---
sidebar: sidebar 
permalink: trident-use/ontap-san-prep.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fcp, asa r2, iscsi, nvme/tcp 
summary: Scopri come prepararti alla configurazione di un backend ONTAP con i driver ONTAP SAN. 
---
= Prepararsi a configurare il backend con i driver ONTAP SAN
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comprendere i requisiti e le opzioni di autenticazione per la configurazione di un backend ONTAP con driver ONTAP SAN.



== Requisiti

Per tutti i backend ONTAP , Trident richiede che almeno un aggregato sia assegnato all'SVM.


NOTE: link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemi ASA r2"^]differiscono dagli altri sistemi ONTAP (ASA, AFF e FAS) nell'implementazione del loro livello di archiviazione.  Nei sistemi ASA r2, al posto degli aggregati vengono utilizzate zone di disponibilità dello storage.  Fare riferimento alink:https://kb.netapp.com/on-prem/ASAr2/ASAr2_KBs/su_create_by_SVM_admin_using_CLI_fails_with_error_No_candidate_aggregates_are_available_for_storage_services["Questo"^] Articolo della Knowledge Base su come assegnare aggregati alle SVM nei sistemi ASA r2.

Ricorda che puoi anche eseguire più di un driver e creare classi di archiviazione che puntano all'uno o all'altro.  Ad esempio, potresti configurare un `san-dev` classe che utilizza il `ontap-san` autista e un `san-default` classe che utilizza il `ontap-san-economy` uno.

Tutti i nodi worker di Kubernetes devono avere installati gli strumenti iSCSI appropriati. Fare riferimento a link:worker-node-prep.html["Preparare il nodo worker"] per i dettagli.



== Autenticare il backend ONTAP

Trident offre due modalità di autenticazione di un backend ONTAP .

* Basato su credenziali: nome utente e password di un utente ONTAP con le autorizzazioni richieste.  Si consiglia di utilizzare un ruolo di accesso di sicurezza predefinito, ad esempio `admin` O `vsadmin` per garantire la massima compatibilità con le versioni ONTAP .
* Basato su certificato: Trident può anche comunicare con un cluster ONTAP utilizzando un certificato installato sul backend.  Qui, la definizione del backend deve contenere valori codificati in Base64 del certificato client, della chiave e del certificato CA attendibile, se utilizzato (consigliato).


È possibile aggiornare i backend esistenti per passare da metodi basati su credenziali a metodi basati su certificati.  Tuttavia, è supportato solo un metodo di autenticazione alla volta.  Per passare a un metodo di autenticazione diverso, è necessario rimuovere il metodo esistente dalla configurazione del backend.


WARNING: Se si tenta di fornire *sia credenziali che certificati*, la creazione del backend fallirà e verrà visualizzato un errore che indica che nel file di configurazione è stato fornito più di un metodo di autenticazione.



=== Abilita l'autenticazione basata sulle credenziali

Trident richiede le credenziali di un amministratore con ambito SVM/cluster per comunicare con il backend ONTAP .  Si consiglia di utilizzare ruoli standard predefiniti come `admin` O `vsadmin` .  Ciò garantisce la compatibilità futura con le future versioni ONTAP che potrebbero esporre API di funzionalità da utilizzare nelle future versioni Trident .  È possibile creare e utilizzare un ruolo di accesso di sicurezza personalizzato con Trident, ma non è consigliato.

Un esempio di definizione del backend sarà simile a questo:

[role="tabbed-block"]
====
.YAML
--
[source, yaml]
----
---
version: 1
backendName: ExampleBackend
storageDriverName: ontap-san
managementLIF: 10.0.0.1
svm: svm_nfs
username: vsadmin
password: password
----
--
.JSON
--
[source, json]
----
{
  "version": 1,
  "backendName": "ExampleBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password"
}

----
--
====
Tieni presente che la definizione del backend è l'unico posto in cui le credenziali vengono archiviate in testo normale.  Dopo aver creato il backend, i nomi utente e le password vengono codificati con Base64 e memorizzati come segreti Kubernetes.  La creazione o l'aggiornamento di un backend è l'unico passaggio che richiede la conoscenza delle credenziali.  Si tratta pertanto di un'operazione riservata esclusivamente all'amministratore, che deve essere eseguita dall'amministratore di Kubernetes/archiviazione.



=== Abilita l'autenticazione basata sul certificato

I backend nuovi ed esistenti possono utilizzare un certificato e comunicare con il backend ONTAP .  Nella definizione del backend sono richiesti tre parametri.

* clientCertificate: valore codificato in Base64 del certificato client.
* clientPrivateKey: valore codificato in Base64 della chiave privata associata.
* trustedCACertificate: valore codificato in Base64 del certificato CA attendibile.  Se si utilizza una CA attendibile, è necessario fornire questo parametro.  Questo può essere ignorato se non viene utilizzata alcuna CA attendibile.


Un flusso di lavoro tipico prevede i seguenti passaggi.

.Passi
. Genera un certificato client e una chiave.  Durante la generazione, impostare il nome comune (CN) sull'utente ONTAP con cui effettuare l'autenticazione.
+
[listing]
----
openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout k8senv.key -out k8senv.pem -subj "/C=US/ST=NC/L=RTP/O=NetApp/CN=admin"
----
. Aggiungere un certificato CA attendibile al cluster ONTAP .  Questa operazione potrebbe essere già gestita dall'amministratore dell'archiviazione.  Ignora se non viene utilizzata alcuna CA attendibile.
+
[listing]
----
security certificate install -type server -cert-name <trusted-ca-cert-name> -vserver <vserver-name>
ssl modify -vserver <vserver-name> -server-enabled true -client-enabled true -common-name <common-name> -serial <SN-from-trusted-CA-cert> -ca <cert-authority>
----
. Installare il certificato client e la chiave (dal passaggio 1) sul cluster ONTAP .
+
[listing]
----
security certificate install -type client-ca -cert-name <certificate-name> -vserver <vserver-name>
security ssl modify -vserver <vserver-name> -client-enabled true
----
. Conferma che il ruolo di accesso alla sicurezza ONTAP supporta `cert` metodo di autenticazione.
+
[listing]
----
security login create -user-or-group-name admin -application ontapi -authentication-method cert
security login create -user-or-group-name admin -application http -authentication-method cert
----
. Verifica l'autenticazione utilizzando il certificato generato.  Sostituire < ONTAP Management LIF> e <nome vserver> con l'IP Management LIF e il nome SVM.
+
[listing]
----
curl -X POST -Lk https://<ONTAP-Management-LIF>/servlets/netapp.servlets.admin.XMLrequest_filer --key k8senv.key --cert ~/k8senv.pem -d '<?xml version="1.0" encoding="UTF-8"?><netapp xmlns="http://www.netapp.com/filer/admin" version="1.21" vfiler="<vserver-name>"><vserver-get></vserver-get></netapp>'
----
. Codifica il certificato, la chiave e il certificato CA attendibile con Base64.
+
[listing]
----
base64 -w 0 k8senv.pem >> cert_base64
base64 -w 0 k8senv.key >> key_base64
base64 -w 0 trustedca.pem >> trustedca_base64
----
. Creare il backend utilizzando i valori ottenuti dal passaggio precedente.
+
[listing]
----
cat cert-backend.json
{
"version": 1,
"storageDriverName": "ontap-san",
"backendName": "SanBackend",
"managementLIF": "1.2.3.4",
"svm": "vserver_test",
"clientCertificate": "Faaaakkkkeeee...Vaaalllluuuueeee",
"clientPrivateKey": "LS0tFaKE...0VaLuES0tLS0K",
"trustedCACertificate": "QNFinfO...SiqOyN",
"storagePrefix": "myPrefix_"
}

tridentctl create backend -f cert-backend.json -n trident
+------------+----------------+--------------------------------------+--------+---------+
|    NAME    | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------+----------------+--------------------------------------+--------+---------+
| SanBackend | ontap-san      | 586b1cd5-8cf8-428d-a76c-2872713612c1 | online |       0 |
+------------+----------------+--------------------------------------+--------+---------+
----




=== Aggiorna i metodi di autenticazione o ruota le credenziali

È possibile aggiornare un backend esistente per utilizzare un metodo di autenticazione diverso o per ruotare le credenziali.  Funziona in entrambi i modi: i backend che utilizzano nome utente/password possono essere aggiornati per utilizzare certificati; i backend che utilizzano certificati possono essere aggiornati per utilizzare nome utente/password.  Per fare ciò, è necessario rimuovere il metodo di autenticazione esistente e aggiungere il nuovo metodo di autenticazione.  Quindi utilizzare il file backend.json aggiornato contenente i parametri richiesti per eseguire `tridentctl backend update` .

[listing]
----
cat cert-backend-updated.json
{
"version": 1,
"storageDriverName": "ontap-san",
"backendName": "SanBackend",
"managementLIF": "1.2.3.4",
"svm": "vserver_test",
"username": "vsadmin",
"password": "password",
"storagePrefix": "myPrefix_"
}

#Update backend with tridentctl
tridentctl update backend SanBackend -f cert-backend-updated.json -n trident
+------------+----------------+--------------------------------------+--------+---------+
|    NAME    | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------+----------------+--------------------------------------+--------+---------+
| SanBackend | ontap-san      | 586b1cd5-8cf8-428d-a76c-2872713612c1 | online |       9 |
+------------+----------------+--------------------------------------+--------+---------+
----

NOTE: Quando si ruotano le password, l'amministratore dell'archiviazione deve prima aggiornare la password per l'utente su ONTAP.  Segue un aggiornamento del backend.  Durante la rotazione dei certificati, è possibile aggiungere più certificati all'utente.  Il backend viene quindi aggiornato per utilizzare il nuovo certificato, dopodiché il vecchio certificato può essere eliminato dal cluster ONTAP .

L'aggiornamento di un backend non interrompe l'accesso ai volumi già creati, né influisce sulle connessioni ai volumi effettuate in seguito.  Un aggiornamento del backend riuscito indica che Trident può comunicare con il backend ONTAP e gestire le future operazioni sui volumi.



=== Crea un ruolo ONTAP personalizzato per Trident

È possibile creare un ruolo cluster ONTAP con privilegi minimi in modo da non dover utilizzare il ruolo di amministratore ONTAP per eseguire operazioni in Trident.  Quando si include il nome utente in una configurazione backend Trident , Trident utilizza il ruolo del cluster ONTAP creato per eseguire le operazioni.

Fare riferimento alink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Generatore di ruoli personalizzati Trident"] per ulteriori informazioni sulla creazione di ruoli personalizzati Trident .

[role="tabbed-block"]
====
.Utilizzo di ONTAP CLI
--
. Crea un nuovo ruolo utilizzando il seguente comando:
+
`security login role create <role_name\> -cmddirname "command" -access all –vserver <svm_name\>`

. Crea un nome utente per l'utente Trident :
+
`security login create -username <user_name\> -application ontapi -authmethod <password\> -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`

. Assegna il ruolo all'utente:
+
`security login modify username <user_name\> –vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Utilizzo di System Manager
--
Eseguire i seguenti passaggi in ONTAP System Manager:

. *Crea un ruolo personalizzato*:
+
.. Per creare un ruolo personalizzato a livello di cluster, selezionare *Cluster > Impostazioni*.
+
(Oppure) Per creare un ruolo personalizzato a livello SVM, selezionare *Archiviazione > VM di archiviazione > `required SVM` > Impostazioni > Utenti e ruoli*.

.. Selezionare l'icona della freccia (*->*) accanto a *Utenti e ruoli*.
.. Selezionare *+Aggiungi* in *Ruoli*.
.. Definisci le regole per il ruolo e clicca su *Salva*.


. *Assegnare il ruolo all'utente Trident *: + Eseguire i seguenti passaggi nella pagina *Utenti e ruoli*:
+
.. Selezionare Aggiungi icona *+* in *Utenti*.
.. Selezionare il nome utente richiesto e selezionare un ruolo nel menu a discesa per *Ruolo*.
.. Fare clic su *Salva*.




--
====
Per maggiori informazioni consultare le seguenti pagine:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Ruoli personalizzati per l'amministrazione di ONTAP"^]Olink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Definisci ruoli personalizzati"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Lavorare con ruoli e utenti"^]




== Autenticare le connessioni con CHAP bidirezionale

Trident può autenticare le sessioni iSCSI con CHAP bidirezionale per `ontap-san` E `ontap-san-economy` conducenti.  Ciò richiede l'abilitazione del `useCHAP` opzione nella definizione del backend.  Quando impostato su `true` Trident configura la sicurezza dell'iniziatore predefinito dell'SVM su CHAP bidirezionale e imposta il nome utente e i segreti dal file backend.  NetApp consiglia di utilizzare CHAP bidirezionale per autenticare le connessioni.  Vedere la seguente configurazione di esempio:

[source, yaml]
----
---
version: 1
storageDriverName: ontap-san
backendName: ontap_san_chap
managementLIF: 192.168.0.135
svm: ontap_iscsi_svm
useCHAP: true
username: vsadmin
password: password
chapInitiatorSecret: cl9qxIm36DKyawxy
chapTargetInitiatorSecret: rqxigXgkesIpwxyz
chapTargetUsername: iJF4heBRT0TCwxyz
chapUsername: uh2aNCLSd6cNwxyz
----

WARNING: IL `useCHAP` Il parametro è un'opzione booleana che può essere configurata solo una volta.  Per impostazione predefinita è impostato su falso.  Dopo averlo impostato su true, non è possibile impostarlo su false.

Inoltre `useCHAP=true` , IL `chapInitiatorSecret` , `chapTargetInitiatorSecret` , `chapTargetUsername` , E `chapUsername` i campi devono essere inclusi nella definizione del backend.  I segreti possono essere modificati dopo la creazione di un backend eseguendo `tridentctl update` .



=== Come funziona

Impostando `useCHAP` su true, l'amministratore dell'archiviazione indica a Trident di configurare CHAP sul backend di archiviazione. Ciò include quanto segue:

* Impostazione di CHAP sull'SVM:
+
** Se il tipo di sicurezza dell'iniziatore predefinito dell'SVM è nessuno (impostato per impostazione predefinita) *e* non ci sono LUN preesistenti già presenti nel volume, Trident imposterà il tipo di sicurezza predefinito su `CHAP` e procedere alla configurazione dell'iniziatore CHAP e del nome utente e dei segreti di destinazione.
** Se l'SVM contiene LUN, Trident non abiliterà CHAP sull'SVM.  Ciò garantisce che l'accesso ai LUN già presenti sulla SVM non sia limitato.


* Configurazione dell'iniziatore CHAP e del nome utente e dei segreti di destinazione; queste opzioni devono essere specificate nella configurazione del backend (come mostrato sopra).


Dopo aver creato il backend, Trident crea un corrispondente `tridentbackend` CRD e memorizza i segreti CHAP e i nomi utente come segreti Kubernetes.  Tutti i PV creati da Trident su questo backend verranno montati e collegati tramite CHAP.



=== Ruota le credenziali e aggiorna i backend

È possibile aggiornare le credenziali CHAP aggiornando i parametri CHAP in `backend.json` file.  Ciò richiederà l'aggiornamento dei segreti CHAP e l'utilizzo di `tridentctl update` comando per riflettere questi cambiamenti.


WARNING: Quando si aggiornano i segreti CHAP per un backend, è necessario utilizzare `tridentctl` per aggiornare il backend.  Non aggiornare le credenziali sul cluster di archiviazione utilizzando ONTAP CLI o ONTAP System Manager poiché Trident non sarà in grado di rilevare queste modifiche.

[listing]
----
cat backend-san.json
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "backendName": "ontap_san_chap",
    "managementLIF": "192.168.0.135",
    "svm": "ontap_iscsi_svm",
    "useCHAP": true,
    "username": "vsadmin",
    "password": "password",
    "chapInitiatorSecret": "cl9qxUpDaTeD",
    "chapTargetInitiatorSecret": "rqxigXgkeUpDaTeD",
    "chapTargetUsername": "iJF4heBRT0TCwxyz",
    "chapUsername": "uh2aNCLSd6cNwxyz",
}

./tridentctl update backend ontap_san_chap -f backend-san.json -n trident
+----------------+----------------+--------------------------------------+--------+---------+
|   NAME         | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+----------------+----------------+--------------------------------------+--------+---------+
| ontap_san_chap | ontap-san      | aa458f3b-ad2d-4378-8a33-1a472ffbeb5c | online |       7 |
+----------------+----------------+--------------------------------------+--------+---------+
----
Le connessioni esistenti non saranno interessate e continueranno a rimanere attive se le credenziali vengono aggiornate da Trident sull'SVM.  Le nuove connessioni utilizzano le credenziali aggiornate, mentre le connessioni esistenti continuano a rimanere attive.  Scollegando e ricollegando i vecchi PV, questi utilizzeranno le credenziali aggiornate.
