---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Scopri come configurare un backend ONTAP con i driver ONTAP NAS. 
---
= Panoramica del driver NAS ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri come configurare un backend ONTAP con i driver ONTAP e Cloud Volumes ONTAP NAS.



== Dettagli del driver ONTAP NAS

Trident fornisce i seguenti driver di archiviazione NAS per comunicare con il cluster ONTAP .  Le modalità di accesso supportate sono: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Autista | Protocollo | Modalità volume | Modalità di accesso supportate | Sistemi di file supportati 


| `ontap-nas`  a| 
NFS SMB
 a| 
File system
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs` , `smb`



| `ontap-nas-economy`  a| 
NFS SMB
 a| 
File system
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs` , `smb`



| `ontap-nas-flexgroup`  a| 
NFS SMB
 a| 
File system
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs` , `smb`

|===
[WARNING]
====
* Utilizzo `ontap-san-economy` solo se si prevede che il conteggio dell'utilizzo del volume persistente sia superiore alink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limiti di volume ONTAP supportati"^] .
* Utilizzo `ontap-nas-economy` solo se si prevede che il conteggio dell'utilizzo del volume persistente sia superiore alink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limiti di volume ONTAP supportati"^] e il `ontap-san-economy` il driver non può essere utilizzato.
* Non usare usare `ontap-nas-economy` se prevedi la necessità di protezione dei dati, ripristino di emergenza o mobilità.
* NetApp non consiglia di utilizzare Flexvol autogrow in tutti i driver ONTAP , ad eccezione di ontap-san.  Come soluzione alternativa, Trident supporta l'uso della riserva snapshot e ridimensiona di conseguenza i volumi Flexvol.


====


== Permessi utente

Trident prevede di essere eseguito come amministratore ONTAP o SVM, in genere utilizzando `admin` utente del cluster o un `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo.

Per le distribuzioni Amazon FSx for NetApp ONTAP , Trident prevede di essere eseguito come amministratore ONTAP o SVM, utilizzando il cluster `fsxadmin` utente o un `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo.  IL `fsxadmin` L'utente è un sostituto limitato dell'utente amministratore del cluster.


NOTE: Se usi il `limitAggregateUsage` parametro, sono richieste le autorizzazioni di amministratore del cluster.  Quando si utilizza Amazon FSx for NetApp ONTAP con Trident, il `limitAggregateUsage` il parametro non funzionerà con il `vsadmin` E `fsxadmin` account utente.  Se si specifica questo parametro, l'operazione di configurazione non riuscirà.

Sebbene sia possibile creare un ruolo più restrittivo all'interno di ONTAP utilizzabile da un conducente Trident , non lo consigliamo.  La maggior parte delle nuove versioni di Trident richiameranno API aggiuntive di cui bisognerebbe tenere conto, rendendo gli aggiornamenti difficili e soggetti a errori.
