---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Scopri come configurare un backend ONTAP con i driver ONTAP SAN. 
---
= Panoramica del driver ONTAP SAN
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri come configurare un backend ONTAP con i driver ONTAP e Cloud Volumes ONTAP SAN.



== Dettagli del driver ONTAP SAN

Trident fornisce i seguenti driver di archiviazione SAN per comunicare con il cluster ONTAP .  Le modalità di accesso supportate sono: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Autista | Protocollo | Modalità volume | Modalità di accesso supportate | Sistemi di file supportati 


| `ontap-san`  a| 
iSCSI SCSI su FC
 a| 
Bloccare
 a| 
RWO, ROX, RWX, RWOP
 a| 
Nessun file system; dispositivo a blocchi raw



| `ontap-san`  a| 
iSCSI SCSI su FC
 a| 
File system
 a| 
RWO, RWOP

ROX e RWX non sono disponibili nella modalità volume Filesystem.
 a| 
`xfs`, `ext3` , `ext4`



| `ontap-san`  a| 
NVMe/TCP

Fare riferimento a<<Considerazioni aggiuntive per NVMe/TCP>> .
 a| 
Bloccare
 a| 
RWO, ROX, RWX, RWOP
 a| 
Nessun file system; dispositivo a blocchi raw



| `ontap-san`  a| 
NVMe/TCP

Fare riferimento a<<Considerazioni aggiuntive per NVMe/TCP>> .
 a| 
File system
 a| 
RWO, RWOP

ROX e RWX non sono disponibili nella modalità volume Filesystem.
 a| 
`xfs`, `ext3` , `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
Bloccare
 a| 
RWO, ROX, RWX, RWOP
 a| 
Nessun file system; dispositivo a blocchi raw



| `ontap-san-economy`  a| 
iSCSI
 a| 
File system
 a| 
RWO, RWOP

ROX e RWX non sono disponibili nella modalità volume Filesystem.
 a| 
`xfs`, `ext3` , `ext4`

|===
[WARNING]
====
* Utilizzo `ontap-san-economy` solo se si prevede che il conteggio dell'utilizzo del volume persistente sia superiore alink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limiti di volume ONTAP supportati"^] .
* Utilizzo `ontap-nas-economy` solo se si prevede che il conteggio dell'utilizzo del volume persistente sia superiore alink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limiti di volume ONTAP supportati"^] e il `ontap-san-economy` il driver non può essere utilizzato.
* Non usare usare `ontap-nas-economy` se prevedi la necessità di protezione dei dati, ripristino di emergenza o mobilità.
* NetApp non consiglia di utilizzare Flexvol autogrow in tutti i driver ONTAP , ad eccezione di ontap-san.  Come soluzione alternativa, Trident supporta l'uso della riserva snapshot e ridimensiona di conseguenza i volumi Flexvol.


====


== Permessi utente

Trident prevede di essere eseguito come amministratore ONTAP o SVM, in genere utilizzando `admin` utente del cluster o un `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo.  Per le distribuzioni Amazon FSx for NetApp ONTAP , Trident prevede di essere eseguito come amministratore ONTAP o SVM, utilizzando il cluster `fsxadmin` utente o un `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo.  IL `fsxadmin` L'utente è un sostituto limitato dell'utente amministratore del cluster.


NOTE: Se usi il `limitAggregateUsage` parametro, sono richieste le autorizzazioni di amministratore del cluster.  Quando si utilizza Amazon FSx for NetApp ONTAP con Trident, il `limitAggregateUsage` il parametro non funzionerà con il `vsadmin` E `fsxadmin` account utente.  Se si specifica questo parametro, l'operazione di configurazione non riuscirà.

Sebbene sia possibile creare un ruolo più restrittivo all'interno di ONTAP utilizzabile da un conducente Trident , non lo consigliamo.  La maggior parte delle nuove versioni di Trident richiameranno API aggiuntive di cui bisognerebbe tenere conto, rendendo gli aggiornamenti difficili e soggetti a errori.



== Considerazioni aggiuntive per NVMe/TCP

Trident supporta il protocollo NVMe (Non-Volatile Memory Express) utilizzando `ontap-san` autista incluso:

* IPv6
* Snapshot e cloni di volumi NVMe
* Ridimensionamento di un volume NVMe
* Importazione di un volume NVMe creato al di fuori di Trident in modo che il suo ciclo di vita possa essere gestito da Trident
* Multipathing nativo NVMe
* Arresto regolare o non regolare dei nodi K8s (24.06)


Trident non supporta:

* DH-HMAC-CHAP supportato nativamente da NVMe
* Multipathing del mappatore di dispositivi (DM)
* Crittografia LUKS



NOTE: NVMe è supportato solo con le API REST ONTAP e non con ONTAPI (ZAPI).
