---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Utilizzando Trident con Amazon FSx for NetApp ONTAP, puoi garantire che i tuoi cluster Kubernetes in esecuzione in Amazon Elastic Kubernetes Service (EKS) possano fornire volumi persistenti di file e blocchi supportati da ONTAP.' 
---
= Installa Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident semplifica la gestione dello storage Amazon FSx for NetApp ONTAP in Kubernetes, consentendo a sviluppatori e amministratori di concentrarsi sulla distribuzione delle applicazioni.

Puoi installare Trident utilizzando uno dei seguenti metodi:

* Timone
* Componente aggiuntivo EKS


Se si desidera utilizzare la funzionalità snapshot, installare il componente aggiuntivo CSI Snapshot Controller.  Fare riferimento alink:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Abilita la funzionalità snapshot per i volumi CSI"^] per maggiori informazioni.



== Installa Trident tramite helm

[role="tabbed-block"]
====
.Identità del pod
--
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Installa Trident utilizzando il seguente esempio:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
Puoi usare il `helm list` comando per rivedere i dettagli dell'installazione quali nome, spazio dei nomi, grafico, stato, versione dell'app e numero di revisione.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.Associazione account di servizio (IRSA)
--
. Aggiungere il repository Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Imposta i valori per *cloud provider* e *cloud identity*:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Puoi usare il `helm list` comando per rivedere i dettagli dell'installazione quali nome, spazio dei nomi, grafico, stato, versione dell'app e numero di revisione.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
Se intendi utilizzare iSCSI, assicurati che iSCSI sia abilitato sul tuo computer client.  Se si utilizza il sistema operativo AL2023 Worker node, è possibile automatizzare l'installazione del client iSCSI aggiungendo il parametro node prep nell'installazione di helm:

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== Installa Trident tramite il componente aggiuntivo EKS

Il componente aggiuntivo Trident EKS include le patch di sicurezza più recenti, le correzioni di bug ed è convalidato da AWS per funzionare con Amazon EKS.  Il componente aggiuntivo EKS consente di garantire costantemente la sicurezza e la stabilità dei cluster Amazon EKS e di ridurre la quantità di lavoro necessaria per installare, configurare e aggiornare i componenti aggiuntivi.



=== Prerequisiti

Prima di configurare il componente aggiuntivo Trident per AWS EKS, assicurati di disporre di quanto segue:

* Un account cluster Amazon EKS con abbonamento aggiuntivo
* Autorizzazioni AWS per il marketplace AWS:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Tipo AMI: Amazon Linux 2 (AL2_x86_64) o Amazon Linux 2 Arm (AL2_ARM_64)
* Tipo di nodo: AMD o ARM
* Un file system Amazon FSx for NetApp ONTAP esistente




=== Abilita il componente aggiuntivo Trident per AWS

[role="tabbed-block"]
====
.Console di gestione
--
. Aprire la console Amazon EKS all'indirizzo https://console.aws.amazon.com/eks/home#/clusters[] .
. Nel riquadro di navigazione a sinistra, seleziona *Cluster*.
. Selezionare il nome del cluster per il quale si desidera configurare il componente aggiuntivo NetApp Trident CSI.
. Seleziona *Componenti aggiuntivi* e poi *Ottieni altri componenti aggiuntivi*.
. Per selezionare il componente aggiuntivo, seguire questi passaggi:
+
.. Scorri verso il basso fino alla sezione *Componenti aggiuntivi di AWS Marketplace* e digita *"Trident"* nella casella di ricerca.
.. Selezionare la casella di controllo nell'angolo in alto a destra della casella Trident by NetApp .
.. Selezionare *Avanti*.


. Nella pagina delle impostazioni *Configura componenti aggiuntivi selezionati*, procedi come segue:
+

NOTE: *Salta questi passaggi se utilizzi l'associazione Pod Identity.*

+
.. Seleziona la *Versione* che desideri utilizzare.
.. Se si utilizza l'autenticazione IRSA, assicurarsi di impostare i valori di configurazione disponibili nelle impostazioni di configurazione facoltative:
+
*** Seleziona la *Versione* che desideri utilizzare.
*** Segui lo *schema di configurazione del componente aggiuntivo* e imposta il parametro *configurationValues* nella sezione *Valori di configurazione* sul role-arn creato nel passaggio precedente (il valore deve essere nel seguente formato):




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
Se si seleziona Sostituisci per il metodo di risoluzione dei conflitti, una o più impostazioni del componente aggiuntivo esistente possono essere sovrascritte con le impostazioni del componente aggiuntivo Amazon EKS.  Se non si abilita questa opzione e si verifica un conflitto con le impostazioni esistenti, l'operazione fallisce.  È possibile utilizzare il messaggio di errore risultante per risolvere il conflitto.  Prima di selezionare questa opzione, assicurati che il componente aggiuntivo Amazon EKS non gestisca impostazioni che devi gestire autonomamente.

. Selezionare *Avanti*.
. Nella pagina *Revisiona e aggiungi*, seleziona *Crea*.
+
Una volta completata l'installazione del componente aggiuntivo, verrà visualizzato il componente aggiuntivo installato.



--
.Interfaccia a riga di comando AWS
--
*1. Crea il `add-on.json` file*:

*Per l'identità del pod, utilizzare il seguente formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*Per l'autenticazione IRSA, utilizzare il seguente formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: Sostituire `<role ARN>` con l'ARN del ruolo creato nel passaggio precedente.

*2. Installa il componente aggiuntivo Trident EKS.*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
Il seguente comando di esempio installa il componente aggiuntivo Trident EKS:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Aggiorna il componente aggiuntivo Trident EKS

[role="tabbed-block"]
====
.Console di gestione
--
. Apri la console Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[] .
. Nel riquadro di navigazione a sinistra, seleziona *Cluster*.
. Selezionare il nome del cluster per il quale si desidera aggiornare il componente aggiuntivo NetApp Trident CSI.
. Selezionare la scheda *Componenti aggiuntivi*.
. Selezionare * Trident by NetApp* e quindi *Modifica*.
. Nella pagina *Configura Trident di NetApp*, procedere come segue:
+
.. Seleziona la *Versione* che desideri utilizzare.
.. Espandi le *Impostazioni di configurazione facoltative* e modificale secondo necessità.
.. Seleziona *Salva modifiche*.




--
.Interfaccia a riga di comando AWS
--
L'esempio seguente aggiorna il componente aggiuntivo EKS:

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* Controlla la versione corrente del tuo componente aggiuntivo FSxN Trident CSI.  Sostituire `my-cluster` con il nome del tuo cluster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Esempio di output:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Aggiornare il componente aggiuntivo alla versione restituita in AGGIORNAMENTO DISPONIBILE nell'output del passaggio precedente.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


Se si rimuove il `--force` opzione e una qualsiasi delle impostazioni del componente aggiuntivo Amazon EKS è in conflitto con le impostazioni esistenti, l'aggiornamento del componente aggiuntivo Amazon EKS non riesce e viene visualizzato un messaggio di errore che consente di risolvere il conflitto.  Prima di specificare questa opzione, assicurati che il componente aggiuntivo Amazon EKS non gestisca le impostazioni che devi gestire, perché tali impostazioni vengono sovrascritte con questa opzione.  Per ulteriori informazioni sulle altre opzioni per questa impostazione, vederelink:https://eksctl.io/usage/addons/["Componenti aggiuntivi"] .  Per ulteriori informazioni sulla gestione sul campo di Amazon EKS Kubernetes, vederelink:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Gestione del campo Kubernetes"] .

--
====


=== Disinstallare/rimuovere il componente aggiuntivo Trident EKS

Per rimuovere un componente aggiuntivo Amazon EKS sono disponibili due opzioni:

* *Conserva il software aggiuntivo sul tuo cluster*: questa opzione rimuove la gestione di qualsiasi impostazione da parte di Amazon EKS.  Rimuove inoltre la possibilità per Amazon EKS di notificare gli aggiornamenti e di aggiornare automaticamente il componente aggiuntivo Amazon EKS dopo aver avviato un aggiornamento.  Tuttavia, mantiene il software aggiuntivo sul cluster.  Questa opzione rende il componente aggiuntivo un'installazione autogestita, anziché un componente aggiuntivo Amazon EKS.  Con questa opzione non ci saranno tempi di inattività per il componente aggiuntivo.  Conservare il `--preserve` opzione nel comando per preservare il componente aggiuntivo.
* *Rimuovere completamente il software aggiuntivo dal cluster*: NetApp consiglia di rimuovere il componente aggiuntivo Amazon EKS dal cluster solo se nel cluster non sono presenti risorse che dipendono da esso.  Rimuovere il `--preserve` opzione dal `delete` comando per rimuovere il componente aggiuntivo.



NOTE: Se al componente aggiuntivo è associato un account IAM, l'account IAM non viene rimosso.

[role="tabbed-block"]
====
.Console di gestione
--
. Aprire la console Amazon EKS all'indirizzo https://console.aws.amazon.com/eks/home#/clusters[] .
. Nel riquadro di navigazione a sinistra, seleziona *Cluster*.
. Selezionare il nome del cluster per il quale si desidera rimuovere il componente aggiuntivo NetApp Trident CSI.
. Selezionare la scheda *Componenti aggiuntivi* e quindi selezionare * Trident by NetApp*.*
. Seleziona *Rimuovi*.
. Nella finestra di dialogo *Rimuovi conferma netapp_trident-operator*, procedere come segue:
+
.. Se desideri che Amazon EKS interrompa la gestione delle impostazioni per il componente aggiuntivo, seleziona *Conserva nel cluster*.  Eseguire questa operazione se si desidera mantenere il software aggiuntivo sul cluster, in modo da poter gestire autonomamente tutte le impostazioni dell'add-on.
.. Inserisci *netapp_trident-operator*.
.. Seleziona *Rimuovi*.




--
.Interfaccia a riga di comando AWS
--
Sostituire `my-cluster` con il nome del tuo cluster, quindi esegui il seguente comando.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
Il seguente comando disinstalla il componente aggiuntivo Trident EKS:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====