= Annotazione del timeout dello spostamento dei dati
:allow-uri-read: 




== Annotazione del timeout dello spostamento dei dati

Durante le operazioni di backup e ripristino, è possibile utilizzare l'annotazione `protect.trident.netapp.io/data-mover-timeout-sec` per configurare il timeout per le operazioni di spostamento dei dati.  Questa annotazione specifica il tempo massimo, in secondi, che un data mover deve attendere per il completamento di un'operazione specifica prima del timeout.  È particolarmente utile nelle situazioni in cui problemi di rete o altri fattori potrebbero causare l'interruzione delle operazioni di trasferimento dei dati.  Aiuta a rilevare e gestire le operazioni bloccate, anziché impostare un timeout generale per l'intero processo.  Ad esempio, se non si registra alcun progresso nel ripristino dei dati del volume a causa di problemi di rete, l'operazione scadrà in base alla durata specificata.

Puoi utilizzare questa annotazione nel tuo file YAML come mostrato di seguito:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
In questo esempio, l'annotazione fallisce `BackupRestore` operazione se non si verifica alcun progresso entro 2 secondi nell'operazione di ripristino.


NOTE: Se il valore dell'annotazione è minore o uguale a 0, l'operazione fallirà immediatamente.
