---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Prima di installare Trident dovresti rivedere questi requisiti generali di sistema.  I backend specifici potrebbero avere requisiti aggiuntivi. 
---
= Requisiti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare Trident dovresti rivedere questi requisiti generali di sistema.  I backend specifici potrebbero avere requisiti aggiuntivi.



== Informazioni critiche su Trident

*È necessario leggere le seguenti informazioni critiche su Trident.*

.<strong>Informazioni critiche su Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 è ora supportato in Trident. Aggiornare Trident prima di aggiornare Kubernetes.
* Trident impone rigorosamente l'uso della configurazione multipathing negli ambienti SAN, con un valore consigliato di `find_multipaths: no` nel file multipath.conf.
+
Utilizzo di una configurazione non multipathing o utilizzo di `find_multipaths: yes` O `find_multipaths: smart` il valore nel file multipath.conf causerà errori di montaggio.  Trident ha raccomandato l'uso di `find_multipaths: no` dalla versione 21.07.



=====
====


== Frontend supportati (orchestratori)

Trident supporta più motori di container e orchestratori, tra cui:

* Anthos On-Prem (VMware) e Anthos su bare metal 1.16
* Kubernetes 1.27 - 1.34
* OpenShift 4.12, 4.14 - 4.19 (se si prevede di utilizzare la preparazione del nodo iSCSI con OpenShift 4.19, la versione minima supportata Trident è 25.06.1.)
+

NOTE: Trident continua a supportare le versioni precedenti di OpenShift in linea conlink:https://access.redhat.com/support/policy/updates/openshift["Ciclo di vita della versione Red Hat Extended Update Support (EUS)"] , anche se si basano su versioni di Kubernetes che non sono più ufficialmente supportate a monte. In questi casi, durante l'installazione Trident , puoi tranquillamente ignorare eventuali messaggi di avviso relativi alla versione di Kubernetes.

* Rancher Kubernetes Engine 2 (RKE2) v1.27.x - 1.34.x
+

NOTE: _Sebbene Trident sia supportato su Rancher Kubernetes Engine 2 (RKE2) versioni 1.27.x - 1.34.x, Trident è attualmente qualificato solo su RKE2 v1.28.5+rke2r1._



Trident funziona anche con una serie di altre offerte Kubernetes completamente gestite e autogestite, tra cui Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Mirantis Kubernetes Engine (MKE) e VMWare Tanzu Portfolio.

Trident e ONTAP possono essere utilizzati come provider di storage perlink:https://kubevirt.io/["KubeVirt"] .


WARNING: Prima di aggiornare un cluster Kubernetes dalla versione 1.25 alla versione 1.26 o successiva su cui è installato Trident , fare riferimento alink:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Aggiornare un'installazione di Helm"] .



== Backend supportati (archiviazione)

Per utilizzare Trident, è necessario uno o più dei seguenti backend supportati:

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp Volumes
* Array NetApp All SAN (ASA)
* Versioni di cluster FAS, AFF, Select o ASA r2 (iSCSI e NVMe/TCP) in locale con supporto limitato di NetApp. Vederelink:https://mysupport.netapp.com/site/info/version-support["Supporto della versione software"] .
* Software NetApp HCI/Element 11 o superiore




== Supporto Trident per KubeVirt e OpenShift Virtualization

.Driver di archiviazione supportati:
Trident supporta i seguenti driver ONTAP per KubeVirt e OpenShift Virtualization:

* ontap-nas
* ontap-nas-economy
* ontap-san (iSCSI, FCP, NVMe su TCP)
* ontap-san-economy (solo iSCSI)


.Punti da considerare:
* Aggiorna la classe di archiviazione per avere `fsType` parametro (ad esempio: `fsType: "ext4"` ) nell'ambiente di virtualizzazione OpenShift.  Se necessario, impostare la modalità volume per bloccare esplicitamente utilizzando `volumeMode=Block` parametro nel `dataVolumeTemplates` per notificare a CDI di creare volumi di dati a blocchi.
* _Modalità di accesso RWX per driver di archiviazione a blocchi_: i driver ontap-san (iSCSI, NVMe/TCP, FC) e ontap-san-economy (iSCSI) sono supportati solo con "volumeMode: Block" (dispositivo raw).  Per questi conducenti, il `fstype` Il parametro non può essere utilizzato perché i volumi sono forniti in modalità dispositivo raw.
* Per i flussi di lavoro di migrazione in tempo reale in cui è richiesta la modalità di accesso RWX, sono supportate le seguenti combinazioni:
+
** NFS + `volumeMode=Filesystem`
** iSCSI + `volumeMode=Block` (dispositivo grezzo)
** NVMe/TCP + `volumeMode=Block` (dispositivo grezzo)
** FC + `volumeMode=Block` (dispositivo grezzo)






== Requisiti delle funzionalità

La tabella seguente riassume le funzionalità disponibili con questa versione di Trident e le versioni di Kubernetes supportate.

[cols="3"]
|===
| Caratteristica | Versione di Kubernetes | Sono richiesti cancelli di funzionalità? 


| Trident  a| 
1,27 - 1,34
 a| 
NO



| Istantanee del volume  a| 
1,27 - 1,34
 a| 
NO



| PVC da istantanee di volume  a| 
1,27 - 1,34
 a| 
NO



| Ridimensionamento PV iSCSI  a| 
1,27 - 1,34
 a| 
NO



| ONTAP CHAP bidirezionale  a| 
1,27 - 1,34
 a| 
NO



| Politiche di esportazione dinamiche  a| 
1,27 - 1,34
 a| 
NO



| Operatore Trident  a| 
1,27 - 1,34
 a| 
NO



| Topologia CSI  a| 
1,27 - 1,34
 a| 
NO

|===


== Sistemi operativi host testati

Sebbene Trident non supporti ufficialmente sistemi operativi specifici, è noto che i seguenti funzionano:

* Versioni di Red Hat Enterprise Linux CoreOS (RHCOS) supportate da OpenShift Container Platform (AMD64 e ARM64)
* RHEL 8+ (AMD64 e ARM64)
+

NOTE: NVMe/TCP richiede RHEL 9 o versione successiva.

* Ubuntu 22.04 o successivo (AMD64 e ARM64)
* Windows Server 2022


Per impostazione predefinita, Trident viene eseguito in un contenitore e, pertanto, può essere eseguito su qualsiasi worker Linux.  Tuttavia, tali lavoratori devono essere in grado di montare i volumi forniti Trident utilizzando il client NFS standard o l'iniziatore iSCSI, a seconda dei backend utilizzati.

IL `tridentctl` L'utilità funziona anche su una qualsiasi di queste distribuzioni di Linux.



== Configurazione host

Tutti i nodi worker nel cluster Kubernetes devono essere in grado di montare i volumi forniti per i pod.  Per preparare i nodi worker, è necessario installare gli strumenti NFS, iSCSI o NVMe in base alla selezione del driver.

link:../trident-use/worker-node-prep.html["Preparare il nodo worker"]



== Configurazione del sistema di archiviazione

Trident potrebbe richiedere modifiche al sistema di archiviazione prima che una configurazione backend possa utilizzarlo.

link:../trident-use/backends.html["Configurare i backend"]



== Porte Trident

Trident necessita di accesso a porte specifiche per la comunicazione.

link:../trident-reference/ports.html["Porte Trident"]



== Immagini dei container e versioni corrispondenti di Kubernetes

Per le installazioni con air gap, l'elenco seguente è un riferimento delle immagini dei contenitori necessarie per installare Trident.  Utilizzare il `tridentctl images` comando per verificare l'elenco delle immagini contenitore necessarie.



=== Immagini del contenitore richieste per Trident 25.06.2

[cols="2"]
|===
| Versioni di Kubernetes | Immagine del contenitore 


| v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.34.0  a| 
* docker.io/netapp/trident:25.06.2
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
* docker.io/netapp/trident-operator:25.06.2 (facoltativo)


|===


=== Immagini del contenitore richieste per Trident 25.06

[cols="2"]
|===
| Versioni di Kubernetes | Immagine del contenitore 


| v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.34.0  a| 
* docker.io/netapp/trident:25.06.0
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
* docker.io/netapp/trident-operator:25.06.0 (facoltativo)


|===