---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: Per iniziare, verifica la prontezza del tuo ambiente operativo, dei cluster applicativi, delle applicazioni e delle licenze.  Assicurati che il tuo ambiente soddisfi questi requisiti per distribuire e utilizzare Trident Protect. 
---
= Requisiti di protezione Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per iniziare, verifica la prontezza del tuo ambiente operativo, dei cluster applicativi, delle applicazioni e delle licenze.  Assicurati che il tuo ambiente soddisfi questi requisiti per distribuire e utilizzare Trident Protect.



== Trident protegge la compatibilità del cluster Kubernetes

Trident Protect è compatibile con un'ampia gamma di offerte Kubernetes completamente gestite e autogestite, tra cui:

* Servizio Amazon Elastic Kubernetes (EKS)
* Motore Google Kubernetes (GKE)
* Servizio Microsoft Azure Kubernetes (AKS)
* Red Hat OpenShift
* SUSE Rancher
* Portafoglio VMware Tanzu
* Kubernetes a monte


[NOTE]
====
* I backup Trident Protect sono supportati solo sui nodi di elaborazione Linux. I nodi di elaborazione Windows non sono supportati per le operazioni di backup.
* Assicurarsi che il cluster su cui si installa Trident Protect sia configurato con un controller snapshot in esecuzione e i relativi CRD.  Per installare un controller snapshot, fare riferimento a https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["queste istruzioni"] .


====


== Compatibilità del backend di archiviazione Trident Protect

Trident Protect supporta i seguenti backend di archiviazione:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP
* Array di archiviazione ONTAP
* Google Cloud NetApp Volumes
* Azure NetApp Files


Assicurati che il tuo backend di archiviazione soddisfi i seguenti requisiti:

* Assicurarsi che lo storage NetApp connesso al cluster utilizzi Trident 24.02 o una versione successiva (si consiglia Trident 24.10).


* Assicurati di disporre di un backend di archiviazione NetApp ONTAP .
* Assicurati di aver configurato un bucket di archiviazione degli oggetti per l'archiviazione dei backup.
* Crea tutti gli spazi dei nomi delle applicazioni che intendi utilizzare per le applicazioni o per le operazioni di gestione dei dati delle applicazioni.  Trident Protect non crea questi namespace per te; se specifichi uno namespace inesistente in una risorsa personalizzata, l'operazione non riuscirà.




== Requisiti per i volumi nas-economy

Trident Protect supporta le operazioni di backup e ripristino sui volumi nas-economy.  Snapshot, cloni e replica SnapMirror su volumi nas-economy non sono attualmente supportati.  È necessario abilitare una directory snapshot per ogni volume nas-economy che si intende utilizzare con Trident Protect.

[NOTE]
====
Alcune applicazioni non sono compatibili con i volumi che utilizzano una directory snapshot.  Per queste applicazioni, è necessario nascondere la directory degli snapshot eseguendo il seguente comando sul sistema di archiviazione ONTAP :

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
È possibile abilitare la directory snapshot eseguendo il seguente comando per ogni volume nas-economy, sostituendo `<volume-UUID>` con l'UUID del volume che vuoi modificare:

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: È possibile abilitare le directory snapshot per impostazione predefinita per i nuovi volumi impostando l'opzione di configurazione del backend Trident `snapshotDir` A `true` .  I volumi esistenti non sono interessati.



== Protezione dei dati con le VM KubeVirt

Trident Protect 24.10 e 24.10.1 e versioni successive hanno un comportamento diverso quando si proteggono le applicazioni in esecuzione su VM KubeVirt.  Per entrambe le versioni è possibile abilitare o disabilitare il blocco e lo sblocco del file system durante le operazioni di protezione dei dati.


NOTE: Durante le operazioni di ripristino, qualsiasi `VirtualMachineSnapshots` creati per una macchina virtuale (VM) non vengono ripristinati.

.Trident protect 24.10
Trident Protect 24.10 non garantisce automaticamente uno stato coerente per i file system delle VM KubeVirt durante le operazioni di protezione dei dati.  Se si desidera proteggere i dati della VM KubeVirt utilizzando Trident Protect 24.10, è necessario abilitare manualmente la funzionalità di congelamento/scongelamento per i file system prima dell'operazione di protezione dei dati.  Ciò garantisce che i file system siano in uno stato coerente.

È possibile configurare Trident Protect 24.10 per gestire il blocco e lo sblocco del file system della VM durante le operazioni di protezione dei dati tramitelink:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["configurazione della virtualizzazione"^] e quindi utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1 e versioni successive
A partire da Trident Protect 24.10.1, Trident Protect blocca e sblocca automaticamente i file system KubeVirt durante le operazioni di protezione dei dati.  Facoltativamente, è possibile disattivare questo comportamento automatico utilizzando il seguente comando:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----


== Requisiti per la replica SnapMirror

La replica NetApp SnapMirror è disponibile per l'uso con Trident Protect per le seguenti soluzioni ONTAP :

* Cluster NetApp FAS, AFF e ASA on-premise
* ONTAP Select NetApp ONTAP
* NetApp Cloud Volumes ONTAP
* Amazon FSx for NetApp ONTAP




=== Requisiti del cluster ONTAP per la replica SnapMirror

Se si prevede di utilizzare la replica SnapMirror, assicurarsi che il cluster ONTAP soddisfi i seguenti requisiti:

* * NetApp Trident*: NetApp Trident deve essere presente sia sul cluster Kubernetes di origine che su quello di destinazione che utilizzano ONTAP come backend.  Trident Protect supporta la replica con la tecnologia NetApp SnapMirror utilizzando classi di archiviazione supportate dai seguenti driver:
+
** `ontap-nas`: NFS
** `ontap-san`: iSCSI
** `ontap-san`: FC
** `ontap-san`: NVMe/TCP (richiede almeno la versione ONTAP 9.15.1)


* *Licenze*: le licenze asincrone ONTAP SnapMirror che utilizzano il bundle Data Protection devono essere abilitate sia sul cluster ONTAP di origine che su quello di destinazione.  Fare riferimento a https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Panoramica delle licenze SnapMirror in ONTAP"^] per maggiori informazioni.
+
A partire da ONTAP 9.10.1, tutte le licenze vengono fornite come file di licenza NetApp (NLF), ovvero un singolo file che abilita più funzionalità.  Fare riferimento alink:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licenze incluse con ONTAP One"^] per maggiori informazioni.

+

NOTE: È supportata solo la protezione asincrona SnapMirror .





=== Considerazioni sul peering per la replica SnapMirror

Se intendi utilizzare il peering backend di archiviazione, assicurati che il tuo ambiente soddisfi i seguenti requisiti:

* *Cluster e SVM*: i backend di archiviazione ONTAP devono essere peered.  Fare riferimento a https://docs.netapp.com/us-en/ontap/peering/index.html["Panoramica del peering di cluster e SVM"^] per maggiori informazioni.
+

NOTE: Assicurarsi che i nomi SVM utilizzati nella relazione di replica tra due cluster ONTAP siano univoci.

* * NetApp Trident e SVM*: le SVM remote peered devono essere disponibili per NetApp Trident sul cluster di destinazione.
* *Backend gestiti*: è necessario aggiungere e gestire i backend di archiviazione ONTAP in Trident Protect per creare una relazione di replica.




=== Configurazione Trident / ONTAP per la replica SnapMirror

Trident Protect richiede la configurazione di almeno un backend di archiviazione che supporti la replica sia per i cluster di origine che per quelli di destinazione.  Se i cluster di origine e di destinazione sono gli stessi, l'applicazione di destinazione dovrebbe utilizzare un backend di archiviazione diverso da quello dell'applicazione di origine per ottenere la migliore resilienza.



=== Requisiti del cluster Kubernetes per la replica SnapMirror

Assicurati che i tuoi cluster Kubernetes soddisfino i seguenti requisiti:

* *Accessibilità ad AppVault*: sia i cluster di origine che quelli di destinazione devono avere accesso alla rete per leggere e scrivere su AppVault per la replica degli oggetti applicativi.
* *Connettività di rete*: configura le regole del firewall, le autorizzazioni dei bucket e le liste consentite di IP per abilitare la comunicazione tra entrambi i cluster e AppVault attraverso le WAN.



NOTE: Molti ambienti aziendali implementano rigide policy firewall sulle connessioni WAN.  Verificare questi requisiti di rete con il team dell'infrastruttura prima di configurare la replica.
