---
sidebar: sidebar 
permalink: trident-reference/trident-cl.html 
keywords: command-line, options, logging, kubernetes, docker, ports 
summary: 'Trident espone diverse opzioni della riga di comando per l"orchestratore Trident e comunica tramite determinate porte.' 
---
= Opzioni della riga di comando
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident espone diverse opzioni della riga di comando per l'orchestratore Trident .  Puoi utilizzare queste opzioni per modificare la tua distribuzione.



== Registrazione

`-debug`:: Abilita l'output di debug.
`-loglevel <level>`:: Imposta il livello di registrazione (debug, info, warn, error, fatal).  Per impostazione predefinita è info.




== Kubernetes

`-k8s_pod`:: Utilizzare questa opzione o `-k8s_api_server` per abilitare il supporto Kubernetes.  Impostando questa opzione, Trident utilizzerà le credenziali dell'account di servizio Kubernetes del pod contenente per contattare il server API.  Funziona solo quando Trident viene eseguito come pod in un cluster Kubernetes con account di servizio abilitati.
`-k8s_api_server <insecure-address:insecure-port>`:: Utilizzare questa opzione o `-k8s_pod` per abilitare il supporto Kubernetes.  Se specificato, Trident si connette al server API Kubernetes utilizzando l'indirizzo e la porta non sicuri forniti.  Ciò consente di distribuire Trident al di fuori di un pod; tuttavia, supporta solo connessioni non sicure al server API.  Per connettersi in modo sicuro, distribuire Trident in un pod con `-k8s_pod` opzione.




== Docker

`-volume_driver <name>`:: Nome del driver utilizzato durante la registrazione del plugin Docker.  Predefinito su `netapp` .
`-driver_port <port-number>`:: Ascolta su questa porta anziché su un socket di dominio UNIX.
`-config <file>`:: Obbligatorio; è necessario specificare questo percorso per un file di configurazione backend.




== RIPOSO

`-address <ip-or-host>`:: Specifica l'indirizzo su cui il server REST di Trident deve essere in ascolto.  Il valore predefinito è localhost.  Quando si ascolta su localhost ed è in esecuzione all'interno di un pod Kubernetes, l'interfaccia REST non è direttamente accessibile dall'esterno del pod.  Utilizzo `-address ""` per rendere l'interfaccia REST accessibile dall'indirizzo IP del pod.
+
--

CAUTION: L'interfaccia REST Trident può essere configurata per ascoltare e servire solo su 127.0.0.1 (per IPv4) o [::1] (per IPv6).

--
`-port <port-number>`:: Specifica la porta su cui il server REST di Trident deve essere in ascolto.  Il valore predefinito è 8000.
`-rest`:: Abilita l'interfaccia REST.  Il valore predefinito è true.

